const translations = {
  "en": {
    "siteTitle": "1701 Industries",
    "metaDescription": "1701 Industries is a Lisbon-based design-led infrastructure, technology and place-making company creating technology-enabled spaces where sustainable infrastructure, architecture, heritage and user experience work together.",
    "brand": "1701 Industries",
    "nav": {
      "home": "Home",
      "founding": "Founding",
      "about": "About",
      "capabilities": "Capabilities",
      "lisbon": "Why Lisbon",
      "contact": "Contact"
    },
    "heroEyebrow": "Lisbon, Portugal · Europe to Japan",
    "heroTitle": "Designing technology-enabled spaces where infrastructure, architecture, heritage, and user experience work together.",
    "heroText": "1701 Industries is a design-led infrastructure, technology and place-making company. It builds systems that allow modern technology, sustainable energy, architecture, heritage and community spaces to work together as one experience.",
    "heroPrimary": "Discuss a project",
    "heroSecondary": "View company overview",
    "focusTitle": "Company focus",
    "focusP1": "1701 Industries does not start with technology. It starts with the environment the technology has to live inside: the building, the street, the user, the operator, the community and the long-term value of the place.",
    "focusP2": "Most companies install chargers, add solar panels or place technology into a building. 1701 asks how the full ecosystem works for the user, the energy source, the cost model, the architecture, the public experience and the commercial operator.",
    "focusP3": "The result is a company focused on technology-enabled spaces that are functional, commercially viable and culturally respectful, with Lisbon as the European base and Japan, the UK and the EU in view.",
    "metricBaseLabel": "Base",
    "metricBaseValue": "Lisbon, Portugal",
    "metricFocusLabel": "Legacy",
    "metricFocusValue": "Satēra · London",
    "metricApproachLabel": "Approach",
    "metricApproachValue": "Place-led systems",
    "metricPositionLabel": "Outlook",
    "metricPositionValue": "EU · UK · Japan",
    "homeBandTitle": "The environment comes first. The technology has to belong there.",
    "homeBandText": "Infrastructure only succeeds when design and functionality operate as one engine: seamless for the user, practical for the operator, viable for the owner and respectful to the place it occupies.",
    "homeOverviewTitle": "From EV charging to complete infrastructure ecosystems.",
    "homeOverviewP1": "1701 Industries evolved from Satēra, a London-founded company created during the COVID-19 period by former Apple and British Aerospace employees. Satēra originally focused on electric vehicle charging, but the founders quickly identified that EV charging was only one part of a much larger infrastructure challenge.",
    "homeOverviewP2": "The real issue was the complete ecosystem: energy availability, power source, cost, user experience, public access, private use, commercial deployment and how infrastructure could integrate into existing places without damaging architecture, landscape, heritage or community identity.",
    "homeOverviewP3": "This led to a wider design philosophy: infrastructure should not feel like machinery imposed onto a place. It should work with the building, the surrounding environment, the people who use it and the cultural value of the location.",
    "actionTitle": "How we work",
    "actionText": "1701 Industries works with partners, clients and stakeholders to preserve, improve and activate buildings and spaces through sustainable infrastructure, software-enabled systems, design thinking and material-led execution. The work connects energy, technology, architecture, heritage and community value into practical commercial outcomes.",
    "foundingEyebrow": "Founding",
    "foundingTitle": "From Satēra to 1701 Industries.",
    "foundingIntro": "1701 Industries grew from Satēra, a London-founded company created during the COVID-19 period by former Apple and British Aerospace employees. The first focus was electric vehicle charging, but that work revealed a bigger question: how should energy, mobility, buildings and user experience operate as one system?",
    "foundingP1": "EV charging was the visible problem, but not the whole problem. A successful electric mobility ecosystem depends on the availability of power, where that energy comes from, cost to the user, software, hardware, public access, private use, commercial deployment and a seamless everyday experience.",
    "foundingP2": "The founders were influenced by the idea that technology is only successful when hardware, software, materials, architecture and user experience operate together. That thinking moved Satēra beyond individual chargers and towards a wider infrastructure ecosystem for homes, public locations, commercial spaces and communities.",
    "foundingP3": "The wider design principle became clear: modern infrastructure should not destroy the landscape, surroundings or identity of a place. It should coexist with architecture, communities and heritage, using software, hardware, materials and spatial thinking to make the environment more useful rather than more cluttered.",
    "foundingP4": "The move from London to Lisbon marked a new chapter. 1701 Industries was created as the European evolution of that original thinking: a company focused on design-led infrastructure, sustainable energy systems, technology integration, adaptive reuse and culturally sensitive commercial spaces.",
    "foundingRationale": "Founding rationale",
    "foundingBullet1": "Originated from London-based Satēra",
    "foundingBullet2": "Moved from EV charging to full infrastructure ecosystems",
    "foundingBullet3": "Built around hardware, software, materials and architecture working together",
    "foundingBullet4": "Re-established in Lisbon as a European place-making and infrastructure company",
    "legacyLabel": "Satēra legacy",
    "legacyTitle": "Original EV ecosystem and sustainable infrastructure thinking",
    "legacyText": "Satēra began with EV charging, but the lasting insight was that a charger alone is not the solution. Power, storage, software, access, cost, architecture and the user journey all have to work together before infrastructure becomes useful.",
    "foundersLabel": "Founders",
    "foundersTitle": "Design, engineering and systems thinking",
    "foundersText": "The original vision combined design and technology experience from Apple with aerospace and engineering discipline from British Aerospace. That background shaped a company focused on infrastructure as a complete experience: hardware, software, materials, architecture, energy and operations.",
    "aboutTitle": "A design-led infrastructure, technology and place-making company.",
    "aboutP1": "1701 Industries is not a generic venture platform. Venture-building is a secondary capability. The core company is focused on design-led infrastructure, technology integration, architecture, sustainability and place-making.",
    "aboutP2": "It develops technology-enabled spaces, sustainable energy systems and commercial environments where architecture, heritage, community and modern functionality coexist. The company is strongest where a place needs to be preserved, improved or activated without losing its identity.",
    "aboutP3": "The Lisbon base is intended to become a living demonstration of the 1701 model: a restored heritage environment that combines work, living, public-facing commercial use, solar generation, battery storage, smart systems and community activation.",
    "principlesTitle": "Operating principles",
    "principle1": "Technology must serve the place",
    "principle2": "Energy must be practical, resilient and commercially clear",
    "principle3": "Architecture and materials must carry the experience",
    "principle4": "Heritage, culture and community must be protected",
    "capabilitiesTitle": "Capabilities",
    "capabilitiesIntro": "The company’s capabilities are organised around five core pillars, with LAB16, the Satēra legacy and the ENN partnership sitting within the wider 1701 Industries structure.",
    "cap1Title": "Sustainable Infrastructure",
    "cap1Text": "Solar, battery storage, EV ecosystems, energy availability, cost efficiency and resilient power systems designed as part of a complete environment rather than isolated equipment.",
    "cap2Title": "Technology & Software Systems",
    "cap2Text": "The digital layer that makes infrastructure usable, measurable, seamless and commercially manageable for users, operators, owners and stakeholders.",
    "cap3Title": "Architecture & Materials",
    "cap3Text": "Integrating modern systems into existing buildings, heritage spaces, commercial environments and community assets through material-led and spatially sensitive execution.",
    "cap4Title": "User Experience & Operations",
    "cap4Text": "Making the system feel seamless for the end user, operator, client, tenant, visitor or community while keeping the operating model practical and commercially useful.",
    "cap5Title": "Culture, Heritage & Community",
    "cap5Text": "Ensuring technology improves a place rather than erasing its character, with attention to architecture, neighbourhood identity, cultural value and public-facing experience.",
    "cap6Title": "LAB16",
    "cap6Text": "The innovation lab for immersive technology, training systems, digital prototyping and technical product development within the broader 1701 Industries ecosystem.",
    "cap7Title": "Satēra Legacy",
    "cap7Text": "The original EV ecosystem and sustainable infrastructure thinking that shaped 1701’s approach to energy, mobility, software, hardware, materials and user experience.",
    "cap8Title": "ENN Partnership",
    "cap8Text": "A separate lifestyle and cultural-commerce partnership with Japan that sits under 1701’s broader ability to create spaces, brands, systems and cross-border platforms, without defining the whole company.",
    "lisbonTitle": "Lisbon is the operating base and proof-of-concept environment.",
    "lis1Title": "European position",
    "lis1Text": "Lisbon provides a practical EU base for sustainable infrastructure, adaptive reuse, technology integration and international coordination.",
    "lis2Title": "Bridge to the UK and Japan",
    "lis2Text": "1701 is positioned to connect Portuguese and European opportunity with UK access and Japanese partnerships, including the ENN partnership.",
    "lis3Title": "Heritage and renewal",
    "lis3Text": "The city provides a strong context for projects where modern systems must coexist with architecture, history, neighbourhoods and cultural value.",
    "lis4Title": "Practical execution",
    "lis4Text": "Portugal offers room to structure, test and demonstrate integrated spaces with a serious European and international outlook.",
    "contactTitle": "Open to serious conversations.",
    "contactText": "We welcome discussions with clients, developers, landlords, strategic partners, institutions, operators, funding stakeholders and Japan-Europe partners interested in technology-enabled spaces, sustainable infrastructure, adaptive reuse and culturally sensitive commercial execution.",
    "contactEmailLabel": "Email",
    "contactEmail": "hello@1701industries.com",
    "contactPrimary": "Email 1701 Industries",
    "footerStatement": "1701 Industries designs and builds technology-enabled spaces where sustainable infrastructure, architecture, heritage and user experience work together.",
    "footerLocations": "Portugal · EU · UK · Japan",
    "tagline": "Designing Value. Building the Future.",
    "copyright": "© 2017-2026, 1701 Industries.com, or its Partners",
    "homeLabel": "Home",
    "overviewLabel": "Overview"
  },
  "pt": {
    "siteTitle": "1701 Industries",
    "metaDescription": "A 1701 Industries é uma empresa sediada em Lisboa, orientada pelo design, infraestrutura, tecnologia e place-making, criando espaços tecnológicos onde infraestrutura sustentável, arquitetura, património e experiência de utilização funcionam em conjunto.",
    "brand": "1701 Industries",
    "nav": {
      "home": "Início",
      "founding": "Fundação",
      "about": "Sobre",
      "capabilities": "Capacidades",
      "lisbon": "Porquê Lisboa",
      "contact": "Contacto"
    },
    "heroEyebrow": "Lisboa, Portugal · Europa para o Japão",
    "heroTitle": "Desenhamos espaços tecnológicos onde infraestrutura, arquitetura, património e experiência funcionam em conjunto.",
    "heroText": "A 1701 Industries é uma empresa de infraestrutura, tecnologia e place-making orientada pelo design. Construímos sistemas que permitem que tecnologia moderna, energia sustentável, arquitetura, património e espaços comunitários funcionem como uma só experiência.",
    "heroPrimary": "Discutir um projeto",
    "heroSecondary": "Ver visão geral da empresa",
    "focusTitle": "Foco da empresa",
    "focusP1": "A 1701 Industries não começa pela tecnologia. Começa pelo ambiente onde a tecnologia tem de viver: o edifício, a rua, o utilizador, o operador, a comunidade e o valor de longo prazo do lugar.",
    "focusP2": "Muitas empresas instalam carregadores, adicionam painéis solares ou colocam tecnologia num edifício. A 1701 pergunta como funciona o ecossistema completo para o utilizador, a fonte de energia, o modelo de custos, a arquitetura, a experiência pública e o operador comercial.",
    "focusP3": "O resultado é uma empresa focada em espaços tecnológicos funcionais, comercialmente viáveis e culturalmente respeitosos, com Lisboa como base europeia e o Japão, o Reino Unido e a UE em perspetiva.",
    "metricBaseLabel": "Base",
    "metricBaseValue": "Lisboa, Portugal",
    "metricFocusLabel": "Legado",
    "metricFocusValue": "Satēra · Londres",
    "metricApproachLabel": "Abordagem",
    "metricApproachValue": "Sistemas orientados pelo lugar",
    "metricPositionLabel": "Perspetiva",
    "metricPositionValue": "UE · Reino Unido · Japão",
    "homeBandTitle": "O ambiente vem primeiro. A tecnologia tem de pertencer ao lugar.",
    "homeBandText": "A infraestrutura só funciona quando design e funcionalidade operam como um só motor: fluida para o utilizador, prática para o operador, viável para o proprietário e respeitosa para o lugar que ocupa.",
    "homeOverviewTitle": "Do carregamento EV a ecossistemas completos de infraestrutura.",
    "homeOverviewP1": "A 1701 Industries evoluiu a partir da Satēra, uma empresa fundada em Londres durante o período da COVID-19 por antigos colaboradores da Apple e da British Aerospace. A Satēra começou focada no carregamento de veículos elétricos, mas os fundadores rapidamente perceberam que esse era apenas um elemento de um desafio de infraestrutura muito maior.",
    "homeOverviewP2": "A verdadeira questão era o ecossistema completo: disponibilidade de energia, fonte de energia, custo, experiência do utilizador, acesso público, utilização privada, implantação comercial e a forma como a infraestrutura poderia integrar-se em lugares existentes sem prejudicar arquitetura, paisagem, património ou identidade comunitária.",
    "homeOverviewP3": "Daí nasceu uma filosofia de design mais ampla: a infraestrutura não deve parecer maquinaria imposta a um lugar. Deve trabalhar com o edifício, o ambiente envolvente, as pessoas que o utilizam e o valor cultural da localização.",
    "actionTitle": "Como trabalhamos",
    "actionText": "A 1701 Industries trabalha com parceiros, clientes e stakeholders para preservar, melhorar e ativar edifícios e espaços através de infraestrutura sustentável, sistemas apoiados por software, pensamento de design e execução orientada por materiais. O trabalho liga energia, tecnologia, arquitetura, património e valor comunitário a resultados comerciais práticos.",
    "foundingEyebrow": "Fundação",
    "foundingTitle": "Da Satēra à 1701 Industries.",
    "foundingIntro": "A 1701 Industries nasceu da Satēra, uma empresa fundada em Londres durante o período da COVID-19 por antigos colaboradores da Apple e da British Aerospace. O primeiro foco foi o carregamento de veículos elétricos, mas esse trabalho revelou uma pergunta maior: como devem energia, mobilidade, edifícios e experiência do utilizador funcionar como um só sistema?",
    "foundingP1": "O carregamento EV era o problema visível, mas não o problema completo. Um ecossistema de mobilidade elétrica bem-sucedido depende da disponibilidade de energia, da sua origem, do custo para o utilizador, do software, do hardware, do acesso público, do uso privado, da implantação comercial e de uma experiência quotidiana fluida.",
    "foundingP2": "Os fundadores foram influenciados pela ideia de que a tecnologia só é bem-sucedida quando hardware, software, materiais, arquitetura e experiência do utilizador funcionam em conjunto. Esse pensamento levou a Satēra além de carregadores individuais e em direção a um ecossistema de infraestrutura mais amplo para habitações, locais públicos, espaços comerciais e comunidades.",
    "foundingP3": "O princípio de design tornou-se claro: a infraestrutura moderna não deve destruir a paisagem, o contexto ou a identidade de um lugar. Deve coexistir com a arquitetura, as comunidades e o património, usando software, hardware, materiais e pensamento espacial para tornar o ambiente mais útil, e não mais saturado.",
    "foundingP4": "A mudança de Londres para Lisboa marcou um novo capítulo. A 1701 Industries foi criada como a evolução europeia desse pensamento original: uma empresa focada em infraestrutura orientada pelo design, sistemas de energia sustentável, integração tecnológica, reutilização adaptativa e espaços comerciais culturalmente sensíveis.",
    "foundingRationale": "Racional da fundação",
    "foundingBullet1": "Originada na Satēra, fundada em Londres",
    "foundingBullet2": "Passou do carregamento EV para ecossistemas completos de infraestrutura",
    "foundingBullet3": "Construída em torno de hardware, software, materiais e arquitetura a trabalhar em conjunto",
    "foundingBullet4": "Reestabelecida em Lisboa como empresa europeia de place-making e infraestrutura",
    "legacyLabel": "Legado Satēra",
    "legacyTitle": "Pensamento original sobre ecossistemas EV e infraestrutura sustentável",
    "legacyText": "A Satēra começou com o carregamento EV, mas a perceção duradoura foi que um carregador, sozinho, não é a solução. Energia, armazenamento, software, acesso, custo, arquitetura e percurso do utilizador têm de funcionar em conjunto antes de a infraestrutura se tornar útil.",
    "foundersLabel": "Fundadores",
    "foundersTitle": "Design, engenharia e pensamento sistémico",
    "foundersText": "A visão original combinou experiência de design e tecnologia da Apple com disciplina aeroespacial e de engenharia da British Aerospace. Essa base moldou uma empresa focada na infraestrutura como experiência completa: hardware, software, materiais, arquitetura, energia e operação.",
    "aboutTitle": "Uma empresa de infraestrutura, tecnologia e place-making orientada pelo design.",
    "aboutP1": "A 1701 Industries não é uma plataforma genérica de ventures. A criação de ventures é uma capacidade secundária. O núcleo da empresa está em infraestrutura orientada pelo design, integração tecnológica, arquitetura, sustentabilidade e place-making.",
    "aboutP2": "Desenvolvemos espaços tecnológicos, sistemas de energia sustentável e ambientes comerciais onde arquitetura, património, comunidade e funcionalidade moderna coexistem. A empresa é mais forte quando um lugar precisa de ser preservado, melhorado ou ativado sem perder a sua identidade.",
    "aboutP3": "A base em Lisboa pretende tornar-se uma demonstração viva do modelo 1701: um ambiente patrimonial restaurado que combina trabalho, habitação, uso comercial aberto ao público, geração solar, armazenamento em bateria, sistemas inteligentes e ativação comunitária.",
    "principlesTitle": "Princípios operacionais",
    "principle1": "A tecnologia deve servir o lugar",
    "principle2": "A energia deve ser prática, resiliente e comercialmente clara",
    "principle3": "Arquitetura e materiais devem sustentar a experiência",
    "principle4": "Património, cultura e comunidade devem ser protegidos",
    "capabilitiesTitle": "Capacidades",
    "capabilitiesIntro": "As capacidades da empresa organizam-se em cinco pilares centrais, com LAB16, o legado Satēra e a parceria ENN dentro da estrutura mais ampla da 1701 Industries.",
    "cap1Title": "Infraestrutura Sustentável",
    "cap1Text": "Solar, armazenamento em bateria, ecossistemas EV, disponibilidade energética, eficiência de custos e sistemas de energia resilientes desenhados como parte de um ambiente completo, não como equipamento isolado.",
    "cap2Title": "Tecnologia e Sistemas de Software",
    "cap2Text": "A camada digital que torna a infraestrutura utilizável, mensurável, fluida e comercialmente gerível para utilizadores, operadores, proprietários e stakeholders.",
    "cap3Title": "Arquitetura e Materiais",
    "cap3Text": "Integração de sistemas modernos em edifícios existentes, espaços patrimoniais, ambientes comerciais e ativos comunitários através de uma execução orientada por materiais e sensível ao espaço.",
    "cap4Title": "Experiência do Utilizador e Operação",
    "cap4Text": "Fazer com que o sistema pareça fluido para o utilizador final, operador, cliente, inquilino, visitante ou comunidade, mantendo o modelo operacional prático e comercialmente útil.",
    "cap5Title": "Cultura, Património e Comunidade",
    "cap5Text": "Garantir que a tecnologia melhora um lugar em vez de apagar o seu caráter, com atenção à arquitetura, identidade de bairro, valor cultural e experiência pública.",
    "cap6Title": "LAB16",
    "cap6Text": "O laboratório de inovação para tecnologia imersiva, sistemas de formação, prototipagem digital e desenvolvimento técnico de produtos dentro do ecossistema mais amplo da 1701 Industries.",
    "cap7Title": "Legado Satēra",
    "cap7Text": "O pensamento original sobre ecossistemas EV e infraestrutura sustentável que moldou a abordagem da 1701 à energia, mobilidade, software, hardware, materiais e experiência do utilizador.",
    "cap8Title": "Parceria ENN",
    "cap8Text": "Uma parceria separada de lifestyle e comércio cultural com o Japão que se enquadra na capacidade mais ampla da 1701 de criar espaços, marcas, sistemas e plataformas transfronteiriças, sem definir toda a empresa.",
    "lisbonTitle": "Lisboa é a base operacional e o ambiente de prova de conceito.",
    "lis1Title": "Posição europeia",
    "lis1Text": "Lisboa proporciona uma base prática na UE para infraestrutura sustentável, reutilização adaptativa, integração tecnológica e coordenação internacional.",
    "lis2Title": "Ponte para o Reino Unido e o Japão",
    "lis2Text": "A 1701 está posicionada para ligar oportunidades portuguesas e europeias ao acesso ao Reino Unido e a parcerias japonesas, incluindo a parceria ENN.",
    "lis3Title": "Património e renovação",
    "lis3Text": "A cidade oferece um contexto forte para projetos onde sistemas modernos têm de coexistir com arquitetura, história, bairros e valor cultural.",
    "lis4Title": "Execução prática",
    "lis4Text": "Portugal oferece espaço para estruturar, testar e demonstrar espaços integrados com uma perspetiva europeia e internacional séria.",
    "contactTitle": "Aberta a conversas sérias.",
    "contactText": "Recebemos conversas com clientes, promotores, senhorios, parceiros estratégicos, instituições, operadores, stakeholders de financiamento e parceiros Japão-Europa interessados em espaços tecnológicos, infraestrutura sustentável, reutilização adaptativa e execução comercial culturalmente sensível.",
    "contactEmailLabel": "Email",
    "contactEmail": "hello@1701industries.com",
    "contactPrimary": "Enviar email à 1701 Industries",
    "footerStatement": "A 1701 Industries desenha e constrói espaços tecnológicos onde infraestrutura sustentável, arquitetura, património e experiência do utilizador funcionam em conjunto.",
    "footerLocations": "Portugal · UE · Reino Unido · Japão",
    "tagline": "Desenhar Valor. Construir o Futuro.",
    "copyright": "© 2017-2026, 1701 Industries.com, ou os seus Parceiros",
    "homeLabel": "Início",
    "overviewLabel": "Visão geral"
  },
  "jp": {
    "siteTitle": "1701 Industries",
    "metaDescription": "1701 Industries は、リスボンを拠点とするデザイン主導のインフラ、テクノロジー、プレイスメイキング企業です。持続可能なインフラ、建築、文化的価値、ユーザー体験が一体となるテクノロジー対応型空間を創出します。",
    "brand": "1701 Industries",
    "nav": {
      "home": "Home",
      "founding": "Founding",
      "about": "About",
      "capabilities": "Capabilities",
      "lisbon": "Why Lisbon",
      "contact": "Contact"
    },
    "heroEyebrow": "ポルトガル・リスボン · ヨーロッパから日本へ",
    "heroTitle": "持続可能なインフラ、建築、文化的価値、ユーザー体験が共に機能する、テクノロジー対応型空間を設計します。",
    "heroText": "1701 Industries は、デザイン主導のインフラ、テクノロジー、プレイスメイキング企業です。現代的なテクノロジー、持続可能なエネルギー、建築、文化的価値、コミュニティ空間が一つの体験として機能するシステムを構築します。",
    "heroPrimary": "プロジェクトを相談する",
    "heroSecondary": "会社概要を見る",
    "focusTitle": "会社の焦点",
    "focusP1": "1701 Industries は、テクノロジーから出発しません。まず考えるのは、そのテクノロジーが存在する環境です。建物、通り、利用者、運営者、コミュニティ、そしてその場所の長期的価値です。",
    "focusP2": "多くの企業は充電器を設置し、太陽光パネルを加え、建物に技術を入れます。1701 は、利用者、エネルギー源、コスト構造、建築、公共体験、商業運営者にとって、エコシステム全体がどう機能するかを問い直します。",
    "focusP3": "その結果、1701 は機能的で、商業的に成立し、文化的にも配慮されたテクノロジー対応型空間をつくる企業として、リスボンを欧州拠点に、日本、英国、EUを見据えています。",
    "metricBaseLabel": "拠点",
    "metricBaseValue": "ポルトガル・リスボン",
    "metricFocusLabel": "レガシー",
    "metricFocusValue": "Satēra · ロンドン",
    "metricApproachLabel": "アプローチ",
    "metricApproachValue": "場所起点のシステム",
    "metricPositionLabel": "視点",
    "metricPositionValue": "EU · 英国 · 日本",
    "homeBandTitle": "環境が先にあり、テクノロジーはそこに自然に属していなければなりません。",
    "homeBandText": "インフラは、デザインと機能が一つのエンジンとして動く時に初めて成功します。利用者にとって滑らかで、運営者にとって実用的で、所有者にとって成立し、その場所に敬意を払うものである必要があります。",
    "homeOverviewTitle": "EV充電から、完全なインフラ・エコシステムへ。",
    "homeOverviewP1": "1701 Industries は、COVID-19期にロンドンで設立された Satēra から発展しました。Satēra は、Apple と British Aerospace の経験を持つ元従業員によって生まれ、当初は電気自動車の充電に焦点を当てていました。しかし創業者たちは、EV充電はより大きなインフラ課題の一部にすぎないと早くから気づきました。",
    "homeOverviewP2": "本当の課題は、エネルギーの可用性、電源、コスト、ユーザー体験、公共利用、私的利用、商業展開、そしてインフラを既存の場所にどう統合し、建築、景観、文化的価値、コミュニティのアイデンティティを損なわないかという、完全なエコシステムでした。",
    "homeOverviewP3": "そこから、より広いデザイン哲学が生まれました。インフラは、場所に押し付けられた機械のように見えるべきではありません。建物、周辺環境、利用する人々、その場所の文化的価値と共に機能するべきです。",
    "actionTitle": "私たちの進め方",
    "actionText": "1701 Industries は、パートナー、クライアント、ステークホルダーと共に、持続可能なインフラ、ソフトウェア対応システム、デザイン思考、素材を重視した実装を通じて、建物や空間を保存し、改善し、活性化します。エネルギー、テクノロジー、建築、文化的価値、コミュニティ価値を、実行可能な商業成果へとつなげます。",
    "foundingEyebrow": "Founding",
    "foundingTitle": "Satēra から 1701 Industries へ。",
    "foundingIntro": "1701 Industries は、COVID-19期にロンドンで設立された Satēra から生まれました。創業には Apple と British Aerospace の経験を持つ元従業員が関わり、最初の焦点は電気自動車の充電でした。しかしその取り組みは、エネルギー、モビリティ、建物、ユーザー体験がどのように一つのシステムとして機能すべきかという、より大きな問いを明らかにしました。",
    "foundingP1": "EV充電は目に見える課題でしたが、全体の課題ではありません。成功する電動モビリティのエコシステムには、電力の可用性、エネルギー源、利用者にとってのコスト、ソフトウェア、ハードウェア、公共アクセス、私的利用、商業展開、そして日常的に滑らかな体験が必要です。",
    "foundingP2": "創業者たちは、テクノロジーはハードウェア、ソフトウェア、素材、建築、ユーザー体験が一体として動く時に初めて成功するという考えに影響を受けました。その考えにより Satēra は、個別の充電器から、住宅、公共空間、商業施設、コミュニティに向けたより広いインフラ・エコシステムへと広がりました。",
    "foundingP3": "デザイン原則は明確でした。現代のインフラは、景観、周辺環境、その場所のアイデンティティを壊すべきではありません。ソフトウェア、ハードウェア、素材、空間設計を用いて、建築、コミュニティ、文化的価値と共存し、環境を雑然とさせるのではなく、より有用にするべきです。",
    "foundingP4": "ロンドンからリスボンへの移行は、新しい章を示しました。1701 Industries は、その初期思想の欧州での進化として生まれました。デザイン主導のインフラ、持続可能なエネルギーシステム、テクノロジー統合、アダプティブリユース、文化的に配慮された商業空間に焦点を当てています。",
    "foundingRationale": "設立の考え方",
    "foundingBullet1": "ロンドン発の Satēra から始まった",
    "foundingBullet2": "EV充電から完全なインフラ・エコシステムへ発展",
    "foundingBullet3": "ハードウェア、ソフトウェア、素材、建築が共に機能する考え方",
    "foundingBullet4": "リスボンで欧州のプレイスメイキング・インフラ企業として再出発",
    "legacyLabel": "Satēra レガシー",
    "legacyTitle": "EVエコシステムと持続可能なインフラの原点",
    "legacyText": "Satēra はEV充電から始まりましたが、持続する洞察は、充電器単体では解決にならないということでした。電力、蓄電、ソフトウェア、アクセス、コスト、建築、ユーザー導線が一緒に機能して初めて、インフラは有用になります。",
    "foundersLabel": "創業者",
    "foundersTitle": "デザイン、エンジニアリング、システム思考",
    "foundersText": "初期の構想は、Apple で培われたデザインとテクノロジーの経験、British Aerospace の航空宇宙・エンジニアリングの規律を組み合わせたものでした。その背景が、ハードウェア、ソフトウェア、素材、建築、エネルギー、運用を含む完全な体験としてインフラを捉える会社を形づくりました。",
    "aboutTitle": "デザイン主導のインフラ、テクノロジー、プレイスメイキング企業。",
    "aboutP1": "1701 Industries は、一般的なベンチャープラットフォームではありません。ベンチャー構築は二次的な能力です。中核は、デザイン主導のインフラ、テクノロジー統合、建築、サステナビリティ、プレイスメイキングにあります。",
    "aboutP2": "建築、文化的価値、コミュニティ、現代的な機能が共存する、テクノロジー対応型空間、持続可能なエネルギーシステム、商業環境を開発します。1701 が最も力を発揮するのは、場所のアイデンティティを失わずに保存、改善、活性化する必要がある時です。",
    "aboutP3": "リスボンの拠点は、1701モデルの生きた実証環境となることを目指しています。修復された歴史的空間の中で、仕事、居住、一般向け商業利用、太陽光発電、蓄電池、スマートシステム、コミュニティ活性化を組み合わせます。",
    "principlesTitle": "運営原則",
    "principle1": "テクノロジーは場所に仕えるべきである",
    "principle2": "エネルギーは実用的で、強く、商業的に明確であるべきである",
    "principle3": "建築と素材が体験を支えるべきである",
    "principle4": "文化的価値、文化、コミュニティを守るべきである",
    "capabilitiesTitle": "Capabilities",
    "capabilitiesIntro": "会社の能力は五つの中核的な柱を中心に構成され、その中に LAB16、Satēra レガシー、ENN パートナーシップが位置づけられます。",
    "cap1Title": "持続可能なインフラ",
    "cap1Text": "太陽光、蓄電池、EVエコシステム、エネルギーの可用性、コスト効率、レジリエントな電力システムを、単体設備ではなく一つの環境の一部として設計します。",
    "cap2Title": "テクノロジーとソフトウェアシステム",
    "cap2Text": "インフラを利用しやすく、測定可能で、滑らかで、商業的に管理しやすいものにするデジタル層です。利用者、運営者、所有者、ステークホルダーを支えます。",
    "cap3Title": "建築と素材",
    "cap3Text": "既存建物、文化的価値のある空間、商業環境、コミュニティ資産に、素材と空間への配慮を重視して現代的なシステムを統合します。",
    "cap4Title": "ユーザー体験と運用",
    "cap4Text": "エンドユーザー、運営者、クライアント、テナント、訪問者、コミュニティにとって滑らかな体験をつくりながら、運用モデルを実用的で商業的に有効なものにします。",
    "cap5Title": "文化・文化的価値・コミュニティ",
    "cap5Text": "テクノロジーが場所の個性を消すのではなく高めるように、建築、地域のアイデンティティ、文化的価値、公共体験に配慮します。",
    "cap6Title": "LAB16",
    "cap6Text": "1701 Industries の広いエコシステムの中で、没入型テクノロジー、トレーニングシステム、デジタルプロトタイピング、技術的な製品開発を担うイノベーションラボです。",
    "cap7Title": "Satēra レガシー",
    "cap7Text": "EVエコシステムと持続可能なインフラに関する原点の考え方が、エネルギー、モビリティ、ソフトウェア、ハードウェア、素材、ユーザー体験に対する1701のアプローチを形づくりました。",
    "cap8Title": "ENN パートナーシップ",
    "cap8Text": "日本との別個のライフスタイルおよび文化商業のパートナーシップです。1701 が持つ空間、ブランド、システム、越境プラットフォームを創出する広い能力の中に位置づけられますが、会社全体を定義するものではありません。",
    "lisbonTitle": "リスボンは運営拠点であり、概念実証の環境です。",
    "lis1Title": "ヨーロッパでの位置",
    "lis1Text": "リスボンは、持続可能なインフラ、アダプティブリユース、テクノロジー統合、国際調整のための実務的なEU拠点です。",
    "lis2Title": "英国と日本への橋渡し",
    "lis2Text": "1701 は、ポルトガルおよび欧州の機会を英国へのアクセスと日本とのパートナーシップにつなげる立場にあり、その中には ENN パートナーシップも含まれます。",
    "lis3Title": "文化的価値と再生",
    "lis3Text": "リスボンは、現代的なシステムが建築、歴史、地域、文化的価値と共存しなければならないプロジェクトに強い文脈を与えます。",
    "lis4Title": "実務的な実行",
    "lis4Text": "ポルトガルは、真剣な欧州および国際的視点を持ちながら、統合型空間を構築し、検証し、実証する余地を提供します。",
    "contactTitle": "真剣な対話を歓迎します。",
    "contactText": "テクノロジー対応型空間、持続可能なインフラ、アダプティブリユース、文化的に配慮された商業実行に関心を持つクライアント、開発事業者、地主、戦略的パートナー、機関、運営者、資金関係者、日本・欧州パートナーとの対話を歓迎します。",
    "contactEmailLabel": "Email",
    "contactEmail": "hello@1701industries.com",
    "contactPrimary": "1701 Industries にメールする",
    "footerStatement": "1701 Industries は、持続可能なインフラ、建築、文化的価値、ユーザー体験が共に機能するテクノロジー対応型空間を設計・構築します。",
    "footerLocations": "ポルトガル · EU · 英国 · 日本",
    "tagline": "価値を設計し、未来を築く。",
    "copyright": "© 2017-2026, 1701 Industries.com, or its Partners",
    "homeLabel": "Home",
    "overviewLabel": "Overview"
  }
};
function getValue(obj, path) { return path.split('.').reduce((acc, part) => acc == null ? undefined : acc[part], obj); }
function setLanguage(lang) {
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang === 'jp' ? 'ja' : lang;
  document.querySelectorAll('[data-i18n]').forEach((el) => { const key = el.getAttribute('data-i18n'); const value = getValue(dict, key); if (value !== undefined) el.textContent = value; });
  const titleEl = document.querySelector('title[data-i18n]'); if (titleEl) titleEl.textContent = dict.siteTitle;
  const metaDesc = document.querySelector('meta[name="description"]'); if (metaDesc) metaDesc.setAttribute('content', dict.metaDescription || translations.en.metaDescription);
  document.querySelectorAll('.lang-btn').forEach(btn => btn.classList.toggle('active', btn.dataset.lang === lang));
  localStorage.setItem('1701-language', lang);
}
const savedLang = localStorage.getItem('1701-language') || 'en';
setLanguage(savedLang);
document.querySelectorAll('.lang-btn').forEach(button => button.addEventListener('click', () => setLanguage(button.dataset.lang)));
const menuToggle = document.querySelector('.menu-toggle'); const mobileNav = document.querySelector('.mobile-nav');
menuToggle?.addEventListener('click', () => mobileNav.classList.toggle('open'));
document.querySelectorAll('.mobile-nav a').forEach(link => link.addEventListener('click', () => mobileNav.classList.remove('open')));
